#Numpy Notes
Numpy notes taken from Learning Python for Data Analysis and Visualization taughe by Jose Portilla

Chris Zeng

Jun, 2015

##Table of Content 
###Commonly used functions in numpy

* from __future__ import division

* where
* sum/mean/std (with dimension reduction arg)
* any/all functions
* unique
* in1d
* save
* load
* savez
* savetxt/loadtxt


In [89]:
import numpy as np

In [90]:
5/2

2

###division (import from __future__)

In [91]:
from __future__ import division

In [92]:
5/2

2.5

###List Comprehension

In [64]:
A = np.array([1,2,3,4])

B= np.array([100,200,300,400])

#Now a boolean array
condition = np.array([True,True,False,False])

#Using a list comprehension
# Initially, the variable A_val, cond, B_val are not specified
# zip is for zipping multiple arrays
answer = [(A_val if cond else B_val) for A_val,B_val,cond in zip(A,B,condition)]

#Show the answer
answer
#Problems include speed issues and multi-dimensional array issues

[1, 2, 300, 400]

###where(cond, true_val, false_val) function
Alternative is where (condition, true_values, false_values)

In [5]:
np.where(condition,A,B)

array([  1,   2, 300, 400])

In [6]:
from numpy.random import randn

In [9]:
# generate 5 by 5 uniformally distributed random variables
arr=randn(5,5)
arr

array([[-0.80230705, -0.82708556,  1.09548897, -0.62123675, -0.27697049],
       [ 0.25304627, -0.04537364,  0.39998762, -0.13664483,  0.42734071],
       [ 1.18896521, -0.57944639,  0.79482857, -0.19692842,  0.46635744],
       [ 0.97062639, -0.6399357 ,  1.42511758, -0.29558955, -1.16192596],
       [ 0.30231984, -1.73222983, -0.39060178,  0.23150141, -0.23403187]])

In [14]:
# if value is less than 0, make it 0, otherwise make it its original value
filtered_arr= np.where(arr<0,0,arr)
filtered_arr

array([[ 0.        ,  0.        ,  1.09548897,  0.        ,  0.        ],
       [ 0.25304627,  0.        ,  0.39998762,  0.        ,  0.42734071],
       [ 1.18896521,  0.        ,  0.79482857,  0.        ,  0.46635744],
       [ 0.97062639,  0.        ,  1.42511758,  0.        ,  0.        ],
       [ 0.30231984,  0.        ,  0.        ,  0.23150141,  0.        ]])

In [17]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# sum up everything
print np.sum(arr)
print arr.sum()

45
45


###sum(dim)/mean(dim)

perform operations on matrix so that it collapse and the 0th/1st dimension retain.

Note: the dim index starts from __0__ (x dimension)

In [27]:
# sum up values across axies (column wise sum)
# column sums: (think it as collapsing the matrix, so that only the 0th dimension, x dim, retains)
print arr.sum(0)

# column sums: (think it as collapsing the matrix, so that only the 1st dimension, y dim, retain)
print arr.sum(1)

[12 15 18]
[ 6 15 24]


In [31]:
arr.mean(0)

array([ 4.,  5.,  6.])

In [32]:
arr.std(0)

array([ 2.44948974,  2.44948974,  2.44948974])

###any & all function

In [37]:
bool_arr = np.array([True,False,True])

__any__ function: return True if there exists at least one element that is true

In [40]:
print any(bool_arr)
print bool_arr.any()

True
True


__all__ function: return True if all elements are true

In [42]:
print all(bool_arr)
print bool_arr.all()

False
False


###Unique function

In [43]:
words = np.array(['lol','I','like','you','and','you','like','me'])

In [46]:
# find unique values
np.unique(words)

array(['I', 'and', 'like', 'lol', 'me', 'you'], 
      dtype='|S4')

###in1d function (useful)
very useful in checking if the elements are within another array

In [50]:
# Answering
# is 'I','hello', and 'world' in the array words RESPECTIVELY

np.in1d(['I','hello','world'],words)

array([ True, False, False], dtype=bool)

#Array Input and Output

In [58]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

###Save and load a single array

In [59]:
# this will save myarray as an numpy file (.npy file)
np.save('myarray',arr)

In [60]:
# overwrite arr
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
# load the saved array
# notice the array is unnamed, so assignment is required
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

###Save and load multiple arrays

In [66]:
arr1=np.arange(0,10)
arr2=np.arange(10,15)
print arr1
print arr2

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14]


###savez function (z for zip)

np.savez("ziparray.npz",x=arr1,y=arr2)

####load multiple array

In [80]:
archived_arr = np.load("ziparray.npz")

In [81]:
archived_arr['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
archived_arr['y']

array([10, 11, 12, 13, 14])

###savetxt() and loadtxt() functions
save text file

In [83]:
arr = np.array([[1,2],[3,4]])

In [85]:
np.savetxt('mytxtarray.txt',arr,delimiter=',')

load text file

In [88]:
txt_arr = np.loadtxt('mytxtarray.txt',delimiter=',')
txt_arr

array([[ 1.,  2.],
       [ 3.,  4.]])